### ISSUE TITLE
Not working at all?

### ISSUE THREAD

**Issue by andresriancho** [Gidsy/django-geoip-utils#5]
Take a look at these steps run in `python manage.py shell` console:

``` python-console
>>> from geoip_utils import core as geoip
>>> from django.http import HttpRequest
>>> r = HttpRequest()
>>> r.META['REMOTE_ADDR'] = '185.165.2.4'
>>> geoip.get_country_name(r)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/andres/PycharmProjects/virtual-envs/lyndsey/local/lib/python2.7/site-packages/geoip_utils/core.py", line 47, in get_country_name
    return geoip.country_name(ip)
  File "/home/andres/PycharmProjects/virtual-envs/lyndsey/local/lib/python2.7/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/home/andres/PycharmProjects/virtual-envs/lyndsey/local/lib/python2.7/site-packages/geoip_utils/core.py", line 15, in _setup
    self._wrapped = GeoIP(cache=CACHE_METHOD)
  File "/home/andres/PycharmProjects/virtual-envs/lyndsey/local/lib/python2.7/site-packages/django/contrib/gis/geoip/base.py", line 91, in __init__
    if not path: raise GeoIPException('GeoIP path must be provided via parameter or the GEOIP_PATH setting.')
GeoIPException: GeoIP path must be provided via parameter or the GEOIP_PATH setting.
```

But on the same session, I verify that the setting is there, and that the dat files are also there...

``` python-console
>>> from django.conf import settings
>>> settings.GEOIP_PATH
'/home/andres/PycharmProjects/virtual-envs/lyndsey/local/lib/python2.7/site-packages/geoip_utils/data'
>>> import os
>>> os.listdir('/home/andres/PycharmProjects/virtual-envs/lyndsey/local/lib/python2.7/site-packages/geoip_utils/data')
['GeoLiteCity.dat', 'GeoIP.dat']
>>> 
```

Ideas?

**Comment by andresriancho** [comment]
Fixed. I had `GEOIP_CACHE_METHOD = geoip.GeoIP.GEOIP_STANDARD` in my settings.py , which broke everything.
